### ISSUE TITLE
Images for documentation

### ISSUE THREAD

**Issue by shuperluu** [ZTube/truenas-gotify-adapter#3]
Hello!

Thanks for this awesome script, is really helpfull for me to use Gotify instead of e-mail.

I will suggest to add some pictures to the readme, as it will showcase the end result and provide some user guidance (for noobs like me). I can provide them.

I will also suggest to add info about the alert level.

What you think?

Regards.

**Comment by ZTube** [comment]
Hi,
sure, feel free to take some screenshots and open a pull request

**Comment by shuperluu** [comment]
Thanks. Capture some of them right now, will open the PR soon and try to have it ready EOW. Will be my 1st PR. Thanks!
